# set some values on github.com/apache/steve
github:
  description: "Apache STeVe -- a set of voting tools"
  homepage: https://steve.apache.org
  labels:
    - python
    - voting
    - stv
  features:
    issues: true
  pull_requests:
    allow_update_branch: true
    del_branch_on_merge: true

# We will publish our site using Pelican, via the asf-site branch
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
pelican:
  whoami: trunk
  target: asf-site
