name: Linting

on:
  push:
    branches: [ trunk ]
    paths:
      - 'v3/**/*.py'
      - '**/linting.yml'
      - 'pylintrc'
      - 'v3/pyproject.toml'
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: v3/pyproject.toml
    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('v3/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install Poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      working-directory: v3  # Set the working directory to v3 where pyproject.toml is located
      run: |
        poetry install --with test,server
    - name: Testing with ruff
      working-directory: v3  # Ensure ruff runs in the correct directory
      run: |
        poetry run ruff check
