name: Type Tests

on:
  push:
    paths:
      - '**/type-tests.yml'
      - '**/*.py'
      - 'requirements.txt'

  pull_request:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install mypy
        python3 -m pip install types-PyYAML
        python3 -m pip install types-requests
    - name: Type testing with mypy
      run: |
          # exclude duplicate module names under wsgi; also standalone.py print syntax error as they cause failure
          # Need to re-enable var-annotated later
          mypy --cache-dir /tmp/ --ignore-missing-imports \
            --exclude pysteve/www/wsgi --exclude pysteve/standalone.py \
            --disable-error-code var-annotated \
            pysteve
